name: Execute Spanner Migrations

on:
  push:
    branches: [ "main" ]
    paths:
      - 'database/**'

jobs:
  run-migration:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: 'projects/947330204934/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'spanner-migrator@gcp-spannerdb-cicd.iam.gserviceaccount.com'

    # Fix: We download the jar directly into a local "plugins" directory
    - name: Download Cloud Spanner Liquibase Extension
      run: |
        mkdir -p plugins
        curl -L https://github.com/cloudspannerecosystem/liquibase-spanner/releases/download/4.27.0/liquibase-spanner-4.27.0-all.jar -o plugins/liquibase-spanner-all.jar

    # Fix: Create directory, download the jar, and open up permissions 
    # so the container's isolated java user can read it.
    - name: Download Cloud Spanner Liquibase Extension
      run: |
        mkdir -p plugins
        curl -L https://github.com/cloudspannerecosystem/liquibase-spanner/releases/download/4.27.0/liquibase-spanner-4.27.0-all.jar -o plugins/liquibase-spanner-all.jar
        chmod -R 755 plugins

    - name: Download Cloud Spanner Liquibase Extension
      run: |
        mkdir -p plugins
        curl -L https://github.com/cloudspannerecosystem/liquibase-spanner/releases/download/4.27.0/liquibase-spanner-4.27.0-all.jar -o plugins/liquibase-spanner-all.jar
        chmod -R 755 plugins

    - name: Run Liquibase Migration
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/liquibase/workspace" \
          -v "${{ github.workspace }}/plugins:/liquibase/internal/lib" \
          -e GOOGLE_APPLICATION_CREDENTIALS="${{ steps.auth.outputs.credentials_file_path }}" \
          liquibase/liquibase:4.27 \
          --changelog-file=/liquibase/workspace/database/changelog.xml \
          --search-path=/liquibase/workspace \
          --url=jdbc:cloudspanner:/projects/gcp-spannerdb-cicd/instances/prod-like-instance/databases/target-app-db \
          update